Fixes build issue on Ubuntu 17.04
When building on Ubuntu 17.04/gcc 6.3.0, the build will fail
due to `error: ‘fabs’ was not declared in this scope`. This just
adds cmath to the includes so it will build properly.